### ISSUE TITLE
TODO Niklas

### ISSUE THREAD

**Issue by NKisser** [Recycling-Heroes-E-Schrottwende/eRecycling#30]
- [x] Leere nachrichten im Chat nicht zulassen
- [ ] Produktfilter implementieren
- [ ] UserID beim erstellen des Produkts
- [ ] UserID bei der Favoritenseite 
- [ ] UserID bei der Profilseite
- [ ] Weiterleitung der Registrierung fixen
- [ ] EMail auf Gültigkeit prüfen
